-- Create gacha master tables and seed existing gacha definitions.

begin;

create table if not exists master.m_gacha (
  gacha_id bigint generated by default as identity primary key,
  gacha_code text not null unique,
  gacha_name text not null,
  description text,
  rarity_rate_n numeric(5,4) not null default 0,
  rarity_rate_r numeric(5,4) not null default 0,
  rarity_rate_sr numeric(5,4) not null default 0,
  rarity_rate_ur numeric(5,4) not null default 0,
  rarity_rate_ssr numeric(5,4) not null default 0,
  image_source text not null default 'supabase',
  image_bucket text,
  image_key text,
  image_version integer not null default 1,
  is_active boolean not null default true,
  published_at timestamptz,
  unpublished_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint m_gacha_publish_window_chk
    check (unpublished_at is null or published_at is null or unpublished_at > published_at),
  constraint m_gacha_image_source_chk
    check (image_source in ('supabase', 's3')),
  constraint m_gacha_image_version_chk
    check (image_version >= 1),
  constraint m_gacha_image_key_format_chk
    check (image_key is null or btrim(image_key) <> ''),
  constraint m_gacha_rate_n_chk check (rarity_rate_n >= 0 and rarity_rate_n <= 1),
  constraint m_gacha_rate_r_chk check (rarity_rate_r >= 0 and rarity_rate_r <= 1),
  constraint m_gacha_rate_sr_chk check (rarity_rate_sr >= 0 and rarity_rate_sr <= 1),
  constraint m_gacha_rate_ur_chk check (rarity_rate_ur >= 0 and rarity_rate_ur <= 1),
  constraint m_gacha_rate_ssr_chk check (rarity_rate_ssr >= 0 and rarity_rate_ssr <= 1),
  constraint m_gacha_rate_total_chk
    check (
      abs((rarity_rate_n + rarity_rate_r + rarity_rate_sr + rarity_rate_ur + rarity_rate_ssr) - 1.0) <= 0.0001
    )
);

create index if not exists m_gacha_active_publish_idx
  on master.m_gacha(is_active, published_at, unpublished_at);

create index if not exists m_gacha_image_lookup_idx
  on master.m_gacha(image_source, image_bucket, image_key);

create table if not exists master.m_gacha_piece (
  gacha_id bigint not null references master.m_gacha(gacha_id) on delete cascade,
  piece_id bigint not null references master.m_piece(piece_id),
  weight integer not null default 1,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (gacha_id, piece_id),
  constraint m_gacha_piece_weight_chk check (weight >= 1)
);

create index if not exists m_gacha_piece_piece_idx
  on master.m_gacha_piece(piece_id);

insert into master.m_gacha (
  gacha_code,
  gacha_name,
  description,
  rarity_rate_n,
  rarity_rate_r,
  rarity_rate_sr,
  rarity_rate_ur,
  rarity_rate_ssr,
  image_source,
  image_bucket,
  image_key,
  image_version,
  is_active,
  published_at,
  unpublished_at
)
values
  (
    'hihen',
    'ひへんガチャ',
    '火辺を含む漢字駒を輩出',
    0.0000,
    0.5000,
    0.3333,
    0.1667,
    0.0000,
    'supabase',
    'gacha-images',
    'assets/gacha/hihen.png',
    1,
    true,
    '2026-03-11 00:00:00+09',
    '2026-04-01 23:59:59+09'
  ),
  (
    'ukanmuri',
    'うかんむりガチャ',
    '守護と加護を司る宀部の駒が当たる守護殿',
    0.0000,
    0.6667,
    0.2222,
    0.1111,
    0.0000,
    'supabase',
    'gacha-images',
    'assets/gacha/ukanmuri.png',
    1,
    true,
    '2026-03-11 00:00:00+09',
    '2026-04-01 23:59:59+09'
  ),
  (
    'shinnyo',
    'しんにょうガチャ',
    '辶のスピードで駆け抜ける機動特化ガチャ',
    0.0000,
    0.6667,
    0.2222,
    0.1111,
    0.0000,
    'supabase',
    'gacha-images',
    'assets/gacha/shinnyo.png',
    1,
    true,
    '2026-03-11 00:00:00+09',
    '2026-04-01 23:59:59+09'
  ),
  (
    'kanken1',
    '漢検１級ガチャ',
    '難字が揃う至高のコレクター向けガチャ',
    0.0000,
    0.0000,
    0.0000,
    0.6000,
    0.4000,
    'supabase',
    'gacha-images',
    'assets/gacha/kanken1.png',
    1,
    true,
    '2026-03-11 00:00:00+09',
    '2026-04-01 23:59:59+09'
  )
on conflict (gacha_code) do update
set
  gacha_name = excluded.gacha_name,
  description = excluded.description,
  rarity_rate_n = excluded.rarity_rate_n,
  rarity_rate_r = excluded.rarity_rate_r,
  rarity_rate_sr = excluded.rarity_rate_sr,
  rarity_rate_ur = excluded.rarity_rate_ur,
  rarity_rate_ssr = excluded.rarity_rate_ssr,
  image_source = excluded.image_source,
  image_bucket = excluded.image_bucket,
  image_key = excluded.image_key,
  image_version = excluded.image_version,
  is_active = excluded.is_active,
  published_at = excluded.published_at,
  unpublished_at = excluded.unpublished_at,
  updated_at = now();

-- Persist rarity labels on currently gacha-targeted pieces.
update master.m_piece as p
set rarity = v.rarity
from (
  values
    ('爆', 'UR'),
    ('煽', 'SR'),
    ('灯', 'R'),
    ('室', 'SR'),
    ('定', 'R'),
    ('安', 'R'),
    ('宋', 'UR'),
    ('辺', 'SR'),
    ('逸', 'R'),
    ('進', 'R'),
    ('逃', 'UR'),
    ('艸', 'UR'),
    ('閹', 'UR'),
    ('賚', 'SSR'),
    ('殲', 'SSR'),
    ('膠', 'UR')
) as v(kanji, rarity)
where p.kanji = v.kanji;

insert into master.m_gacha_piece (gacha_id, piece_id, weight, is_active)
select
  g.gacha_id,
  p.piece_id,
  m.weight,
  true
from (
  values
    ('hihen', '爆', 1),
    ('hihen', '煽', 2),
    ('hihen', '灯', 3),
    ('ukanmuri', '室', 2),
    ('ukanmuri', '定', 3),
    ('ukanmuri', '安', 3),
    ('ukanmuri', '宋', 1),
    ('shinnyo', '辺', 2),
    ('shinnyo', '逸', 3),
    ('shinnyo', '進', 3),
    ('shinnyo', '逃', 1),
    ('kanken1', '艸', 1),
    ('kanken1', '閹', 1),
    ('kanken1', '賚', 1),
    ('kanken1', '殲', 1),
    ('kanken1', '膠', 1)
) as m(gacha_code, piece_kanji, weight)
join master.m_gacha as g on g.gacha_code = m.gacha_code
join master.m_piece as p on p.kanji = m.piece_kanji
on conflict (gacha_id, piece_id) do update
set
  weight = excluded.weight,
  is_active = excluded.is_active,
  updated_at = now();

commit;
